---
title: "Class 8"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    code_download: true
    code_folding: show
date: "2026-09-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Cincy Crashes

```{r}
httr2::request("https://data.cincinnati-oh.gov/resource/rvmt-pkmq.json") |>
  httr2::req_url_query("$limit" = 5) |>
  httr2::req_perform() |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON() -> cincy_crashes
```


## FRED API
```{r}
httr2::request("https://api.stlouisfed.org/fred/series/observations") |>
  httr2::req_url_query(
    series_id = "IHLIDXUSOH",
    api_key = Sys.getenv("FRED_API_KEY"),
    file_type = "json"
  ) |>
  httr2::req_perform() |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON() -> ohio_jobs
ohio_jobs

jobs_df = ohio_jobs[[13]]

# to get data from sept 1, 2026

# (a) to get all the data and then filter the rows that I want
## not the most efficient but correct
dplyr::glimpse(jobs_df) # realized that date is a char
jobs_df |>
  # therefore, I overwrote date into a date column
  dplyr::mutate(
    date = lubridate::ymd(date)
  ) |>
  # used filter to find all dates that are >= Sep 01, 2026
  dplyr::filter(date>= '2026-09-01') -> jobs_df_mod
jobs_df_mod

# (b) use API
httr2::request("https://api.stlouisfed.org/fred/series/observations") |>
  httr2::req_url_query(
    series_id = "IHLIDXUSOH",
    api_key = Sys.getenv("FRED_API_KEY"),
    file_type = "json",
    observation_start="2026-09-01"
  ) |>
  httr2::req_perform() |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON() -> ohio_jobs_sept_2026
ohio_jobs_sept_2026
ohio_jobs_sept_2026_df = ohio_jobs_sept_2026$observations
ohio_jobs_sept_2026_df
```
## USA JOBS API
```{r}
httr2::request("https://data.usajobs.gov/api/search") |>
  httr2::req_url_query(Keyword = "Data Analyst", ResultsPerPage = 500) |>
  httr2::req_headers(
    Host = "data.usajobs.gov",
    "User-Agent" = "nicholg@miamioh.edu",
    "Authorization-Key" = Sys.getenv("USAJOBS_API_KEY")
  ) |>
  httr2::req_perform() |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON(flatten = TRUE) -> usa_jobs_list
usa_jobs_list

usa_df = usa_jobs_list$SearchResult$SearchResultItems
usa_df

jobs_small = usa_df |>
  dplyr::select(
    title = MatchedObjectDescriptor.PositionTitle,
    department = MatchedObjectDescriptor.DepartmentName,
    agency = MatchedObjectDescriptor.OrganizationName,
    location = MatchedObjectDescriptor.PositionLocationDisplay,
    closes = MatchedObjectDescriptor.ApplicationCloseDate
  )

jobs_small |>
  dplyr::filter(
    title == "Data Analyst"
  )

index_data_analyst = jobs_small$title |>
  stringr::str_detect(pattern = 'Data Analyst|Data Analytics')

jobs = jobs_small[index_data_analyst, ]
jobs
```





